---
dist: bionic
language: python

# Cache the big Vagrant boxes
cache:
  directories:
  - /home/travis/.vagrant.d/boxes

install:
# Install VirtualBox
- sudo wget https://download.virtualbox.org/virtualbox/6.1.4/virtualbox-6.1_6.1.4-136177~Ubuntu~bionic_amd64.deb
- sudo dpkg -i virtualbox-6.1_6.1.4-136177~Ubuntu~bionic_amd64.deb

# How did the VirtualBox installation go?
- VBoxManage --version

# Download Vagrant & Install Vagrant package
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
- sudo dpkg -i vagrant_2.2.7_x86_64.deb

# Vagrant correctly installed?
- vagrant --version

script:
- sudo vagrant up
- sudo vagrant ssh -c "echo 'hello world!'"